<!--
FILE: 						<?php echo basename(__FILE__, $_SERVER['PHP_SELF'])."\n"; ?>
TITLE:						Apex Listings - Listing City Select
AUTHORS:					Smit Patel
LAST MODIFIED:		October 4, 2018
DESCRIPTION:			Allows users to login to their profiles or allows new users to create an account
-->
<?php

$title = "Listing City Select";
$file = "listing_city_select.php";
$date = "Nov 21 2018";
$banner = "Listing City Select";
$desc = "Listing City Select Page";
require('header.php');

if (!isset($_SESSION['username_s'])){
    $session_message = [];
    $session_message[] = "Login Required for accessing this page.";
    $_SESSION['cookies_message'] = $session_message;   
    header('Location: ./login.php');
    ob_flush();  //Flush output buffer
}
?>
<script type="text/javascript">     
    $(window).on('load', function () {
        $('.preloader-background').hide();

    });      
</script>
<script type="text/javascript">

	/*NOTE: for the following function to work, on your page
			you have to create a checkbox id'ed as city_toggle
				
	<input type="checkbox"  onclick="toggle(this);" name="city[]" value="0">
			
		and each city checkbox element has to be an named as an 
		array (specifically named "city[]")
		e.g.
			<input type="checkbox" name="city[]" value="1">Ajax
	*/
	function toggle(source) {
        
		checkboxes = document.getElementsByName('city[]');
		for(i = 0; i < checkboxes.length; i++)
		{
            checkboxes[i].checked = source.checked;
            console.log("check\n");
		}
	}
		
</script>
<!-- Image Map Generated by http://www.image-map.net/ -->
<?php

    if ($_SERVER["REQUEST_METHOD"] == "GET") {
        
        // $city_select = isset($_COOKIE['city_select'])?$_COOKIE['city_select']:"8";   
        $city_select = isset($_COOKIE['city_select'])?$_COOKIE['city_select']:0;

    } 

?>
<div class="grid-x" style="padding-right:100px;">
    <div style="height:843px;width:1640px;transform: scale(0.8);" class="cell small-12">
        <img src="./assets/map.PNG" usemap="#image-map">
        <map name="image-map">
            <area target="_self" alt="oshawa" title="oshawa" href="./listing_search.php?city_value=8" coords="857,703,776,656" shape="rect">
            <area target="_self" alt="whitby" title="whitby" href="./listing_search.php?city_value=64" coords="768,733,689,651" shape="rect">
            <area target="_self" alt="ajax" title="ajax" href="./listing_search.php?city_value=1" coords="684,771,613,665" shape="rect">
            <area target="_self" alt="pickering" title="pickering" href="./listing_search.php?city_value=16" coords="515,681,605,800" shape="rect">
            <area target="_self" alt="brooklin" title="brooklin" href="./listing_search.php?city_value=2" coords="724,490,799,559" shape="rect">
            <area target="_self" alt="bowmanville" title="bowmanville" href="./listing_search.php?city_value=4" coords="955,601,1068,672" shape="rect">
            <area target="_self" alt="port perry" title="port perry" href="./listing_search.php?city_value=32" coords="674,312,781,386" shape="rect">
            <area target="_self" alt="clarington" title="clarington" href="./listing_search.php?city_value=128" coords="1078,575,1154,633" shape="rect">
            <area target="_self" alt="courtice" title="courtice" href="./listing_search.php?city_value=256" coords="864,619,942,697" shape="rect">
        </map>
    </div>
</div>

<div class='grid-x py-4'>
    <h2 class='cell small-12 center red-text dosis'>Listing City Select</h2>
    <form class='cell small-12 center row' action="listing_search.php" method='get' enctype="multipart/form-data" >
    <div class="col s12 center">
        <h6 class="grey-text text-lighten-1">Select City</h6>
        <div class="pl-4 ml-4">
        <label class='input-field col s2'>
            <input type="checkbox"  onclick="toggle(this);" name="city[]" value="0" id="all_checkbox">
            <span>Select All</span>
        </label>
        <?php build_checkbox("city", "property" , "value", $city_select) ?>
        </div>
    </div> 
    <div class='input-field col s12 center'>
        <!-- <input type="submit" class="btn waves-effect waves-light cayan lighten-1" name="submit"> -->
        <button class="btn grey darken-2 waves-effect waves-light z-depth-4" name="dsh_post_submit" type="submit">
            Submit <i class="fas fa-check"></i> 
        </button>
    </div>

    </form>
</div>


<?php
require("./footer.php");
?>